#!/usr/bin/env bash
sbt package && SPARK_LOCAL_IP=127.0.0.1 spark-submit --packages com.databricks:spark-csv_2.11:1.3.0 --driver-memory 25G --class Slices --master local[8] target/scala-2.11/hdp-analysis_2.11-1.0.jar
